//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvalik2025Mukachev.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kvalik2025MukachevEntities : DbContext
    {
        public Kvalik2025MukachevEntities()
            : base("name=Kvalik2025MukachevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Direction_Service> Direction_Service { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Qualification> Qualification { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Service> Type_Service { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
